platform :ios,'7.0'
pod 'CocoaLumberjack'
pod 'AFNetworking'  , "~> 2.0"
pod 'GPUImage', '~> 0.1.4'
pod 'Parse', '~> 1.2.19'
pod 'SDWebImage' 
pod 'BlocksKit' 
pod 'PromiseKit', :git => 'https://github.com/nyankichi820/PromiseKit.git'
pod 'FrameAccessor' 
pod 'MTAnimation'
pod 'Canvas'
pod 'Chains'
pod 'ObjectAL-for-iPhone'
pod 'socket.IO'
pod 'STTwitter'
pod 'Facebook-iOS-SDK'
pod 'MYRoutes', '~> 0.1.0'
pod 'UIColor-HexString', '~> 1.1.0'

